### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by neuschaefer**
This PR is a follow-up to #6.

By reconfiguring the PIO/SPI clock rate to frequency requested by flashrom, and filling the USB bulk transfers with more than 1 byte at a time, the net throughput is improved to about 5 Mbit/s (16 MiB are read in 26 seconds).

### CODE REVIEW

**Comment by nezza** [comment]
Uhhhh nice!

I won't have time to test this until the end of the week, please ping if I forget :)

**Comment by neuschaefer** [comment]
ping :)

**Comment by neuschaefer** [comment]
@nezza ping :)

**Comment by 602p** [comment]
Thanks very much for this improvement/fix @neuschaefer to this handy project. The unmodified version worked fine but was absolutely glacial programming a 64MiB flash. Ping @nezza to see if the improved version could become the default + precompiled uf2 image :).

**Comment by nezza** [comment]
Thanks so much :) Merged!

**Pull request merged**
